function createfigure_xy_multi(X1, YMatrix1, Xlabel, Ylabel, Xscale, Yscale, Units, Width, Height, Lgdtitle, Legend, NumColumns)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of loglog x data
%  YMATRIX1:  matrix of loglog y data

%  Auto-generated by MATLAB on 07-Apr-2023 15:34:54

Yn = size(YMatrix1,1);
newcolors = hsv(Yn);

LineStyle = ["-" "--" ":" "-."];

% Create figure
figure1 = figure('Units',Units,'Position',[5 5 5+Width 5+Height],'Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to loglog
plot1 = plot(X1,YMatrix1);
if nargin > 9
    for i=1:Yn
        set(plot1(i),'LineStyle',LineStyle(ceil(i/NumColumns)),'DisplayName',Legend(i),'LineWidth',1.5,'Color',newcolors(i,:));
    end
else
    for i=1:Yn
        set(plot1(i),'LineWidth',1.5,'Color',newcolors(i,:));
    end
end


% Create ylabel
ylabel(Ylabel,'Interpreter','latex');

% Create xlabel
xlabel(Xlabel,'Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on',...
    'XMinorTick','on','XScale',Xscale,'YGrid','on','YMinorTick','on','YScale',...
    Yscale);
axes1.XAxis.Exponent = 3;
% Create legend
if nargin > 9
    legend1 = legend(axes1,'show');
    set(legend1,'Interpreter','latex','Location','best','Orientation','horizontal','NumColumns',NumColumns);
    title(legend1, Lgdtitle, 'Interpreter','latex');
end

