function createfigure(freq, hr, alpha, alpha_c, alpha_hf, XLabel, YLabel, Title, LTitle)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of loglog x data
%  YMATRIX1:  matrix of loglog y data

%  Auto-generated by MATLAB on 24-Mar-2023 23:59:12

newcolors = hsv(length(hr));

% Create figure
figure1 = figure('Name','Figure','Color',[1 1 1],'Units','centimeters','Position',[5 5 5+15 5+15]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

loglog2 = loglog(freq,alpha_c);
set(loglog2,'DisplayName','Classical','Color','k','LineWidth',1.5)

loglog3 = loglog(freq,alpha_hf);
set(loglog3,'LineStyle','-.','DisplayName','HF asymptot.','Color',[0.4 0.4 0.4],'LineWidth',1.5)

loglog1 = loglog(freq,alpha);
for i=1:length(hr)
    set(loglog1(i),'DisplayName',num2str(hr(i)),'Color',newcolors(i,:),'LineWidth',1.5);
end

% Create xlabel
xlabel(XLabel);

% Create ylabel
ylabel(YLabel,'Interpreter','latex');

% Create title
title(Title,'Interpreter','latex');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',11,'XGrid','on',...
    'XMinorTick','on','XScale','log','YGrid','on','YMinorTick','on','YScale',...
    'log');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','eastoutside');
title(legend1, LTitle)